/**
 * PolicyLens - Pre-compiled Verified Sample Policies
 * Provides instant 1-click test policies for judges and demonstrations
 * with verified page evidence, compiled rules, and realistic clauses.
 */

import { PolicyAnalysisResult } from '../types/policy'
import { compilePolicyRules } from './compiler'

export const SAMPLE_POLICIES: Record<string, PolicyAnalysisResult> = {
  hdfc_optima: {
    overview: {
      insurer: 'HDFC ERGO General Insurance',
      plan_name: 'Optima Secure Individual Health Plan',
      sum_insured: '₹5,00,000',
      policy_type: 'Individual Health Indemnity',
      total_pages: 28,
      uin: 'HDFHLIP21175V012021',
    },
    rules: [
      {
        id: 'hdfc_1',
        category: 'sum_insured',
        rule_name: 'Base Sum Insured Protection',
        value: '₹5,00,000',
        description: 'Aggregate maximum claim indemnity of Rs 5,00,000 available across the active policy term.',
        status: 'covered',
        conditions: [],
        page_number: 3,
        section_name: 'Section 1 - Schedule of Benefits',
        evidence_text: 'The Company maximum liability for all admissible claims during the policy year shall not exceed the Sum Insured of Rs 5,00,000 specified in the Schedule.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_2',
        category: 'waiting_period',
        rule_name: 'Specific Illness 24-Month Waiting Period',
        value: '24 months',
        description: 'Mandatory 24 months continuous coverage required before joint replacement, cataract, hernia, and stones are eligible.',
        status: 'conditionally_covered',
        conditions: ['Joint replacement', 'cataract', 'hernia', 'cholecystectomy'],
        page_number: 11,
        section_name: 'Section 4.1 - Waiting Periods',
        evidence_text: 'A waiting period of 24 consecutive months of continuous coverage applies to joint replacement surgery, cataract surgery, benign prostatic hypertrophy, and hernia repair.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_3',
        category: 'waiting_period',
        rule_name: 'Initial 30-Day Waiting Period',
        value: '30 days',
        description: 'No medical expenses admissible within first 30 days from policy inception except accidental injuries.',
        status: 'conditionally_covered',
        conditions: ['Non-accidental claims'],
        page_number: 11,
        section_name: 'Section 4.1 - Initial Waiting Period',
        evidence_text: 'Expenses related to the treatment of any illness within 30 days from the first policy commencement date shall be excluded except claims arising from accidental bodily injury.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_4',
        category: 'room_rent',
        rule_name: 'Room Category Eligibility',
        value: 'Single Private Room',
        description: 'Eligible room category is Single Private AC room. Upgrading to Deluxe Suite incurs room excess fees.',
        status: 'conditionally_covered',
        conditions: ['Single private AC room'],
        page_number: 7,
        section_name: 'Section 2.1 - Inpatient Care',
        evidence_text: 'Room rent, boarding and nursing charges are covered up to Single Private AC Room category. In case of admission to higher category room, excess room fee shall be borne by the insured.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_5',
        category: 'co_payment',
        rule_name: 'Senior Citizen Co-pay (Age 60+)',
        value: '20%',
        description: '20% co-payment deducted from admissible claim amount if patient age is 60 or older on date of admission.',
        status: 'conditionally_covered',
        conditions: ['Patient age >= 60'],
        page_number: 16,
        section_name: 'Section 5.3 - Co-payment Clause',
        evidence_text: 'A co-payment of 20% shall be borne by the insured person on every admissible claim if the insured person is aged 60 years or above on the date of hospital admission.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_6',
        category: 'sub_limit',
        rule_name: 'Cataract Surgery Sub-Limit',
        value: '₹40,000 per eye',
        description: 'Cataract treatment capped at Rs 40,000 per eye per policy year.',
        status: 'conditionally_covered',
        conditions: ['Cataract surgery'],
        page_number: 8,
        section_name: 'Section 2.4 - Specific Capping',
        evidence_text: 'Coverage for cataract surgery including cost of lens is limited to Rs 40,000 per eye during each policy year.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_7',
        category: 'deductible',
        rule_name: 'Zero Voluntary Deductible',
        value: '₹0',
        description: 'No deductible applies to standard inpatient hospitalization claims.',
        status: 'covered',
        conditions: [],
        page_number: 17,
        section_name: 'Section 6 - Cost Sharing',
        evidence_text: 'Standard policy operates with Nil compulsory deductible on inpatient hospitalizations.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'hdfc_8',
        category: 'exclusion',
        rule_name: 'Cosmetic & Aesthetic Surgery Exclusion',
        value: 'Not covered',
        description: 'Plastic surgery or aesthetic procedures not medically necessary are excluded.',
        status: 'not_covered',
        conditions: [],
        page_number: 14,
        section_name: 'Section 4.3 - Permanent Exclusions',
        evidence_text: 'Expenses for cosmetic or aesthetic surgery or any treatment which is not medically necessary are permanently excluded.',
        confidence: 'high',
        evidence_validated: true,
      },
    ],
    pages: [
      { page_number: 3, text: 'The Company maximum liability for all admissible claims during the policy year shall not exceed the Sum Insured of Rs 5,00,000 specified in the Schedule.', char_count: 154 },
      { page_number: 7, text: 'Room rent, boarding and nursing charges are covered up to Single Private AC Room category. In case of admission to higher category room, excess room fee shall be borne by the insured.', char_count: 188 },
      { page_number: 8, text: 'Coverage for cataract surgery including cost of lens is limited to Rs 40,000 per eye during each policy year.', char_count: 108 },
      { page_number: 11, text: 'A waiting period of 24 consecutive months of continuous coverage applies to joint replacement surgery, cataract surgery, benign prostatic hypertrophy, and hernia repair. Expenses related to the treatment of any illness within 30 days from the first policy commencement date shall be excluded except claims arising from accidental bodily injury.', char_count: 345 },
      { page_number: 14, text: 'Expenses for cosmetic or aesthetic surgery or any treatment which is not medically necessary are permanently excluded.', char_count: 118 },
      { page_number: 16, text: 'A co-payment of 20% shall be borne by the insured person on every admissible claim if the insured person is aged 60 years or above on the date of hospital admission.', char_count: 167 },
      { page_number: 17, text: 'Standard policy operates with Nil compulsory deductible on inpatient hospitalizations.', char_count: 88 },
    ],
    total_pages: 28,
    scanned_pdf_warning: false,
    extraction_stats: {
      total_rules: 8,
      coverage_count: 2,
      exclusion_count: 1,
      waiting_period_count: 2,
      limit_count: 3,
      eligibility_count: 0,
      claim_requirement_count: 0,
      high_confidence: 8,
      medium_confidence: 0,
      low_confidence: 0,
      validated_count: 8,
    },
    processing_time_ms: 1250,
  },

  star_health: {
    overview: {
      insurer: 'Star Health and Allied Insurance',
      plan_name: 'Star Comprehensive Health Insurance',
      sum_insured: '₹10,00,000',
      policy_type: 'Family Floater / Individual',
      total_pages: 34,
      uin: 'SHAHLIP22028V072122',
    },
    rules: [
      {
        id: 'star_1',
        category: 'sum_insured',
        rule_name: 'Sum Insured Ceiling',
        value: '₹10,00,000',
        description: 'Ten Lakhs aggregate sum insured per policy term.',
        status: 'covered',
        conditions: [],
        page_number: 4,
        section_name: 'Coverage Table',
        evidence_text: 'Aggregate maximum indemnity shall not exceed the Sum Insured of Rs 10,00,000 as stated in the policy schedule.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'star_2',
        category: 'waiting_period',
        rule_name: 'Pre-existing Diseases 36-Month Waiting Period',
        value: '36 months',
        description: 'Declared pre-existing medical conditions covered after 36 months of continuous coverage.',
        status: 'conditionally_covered',
        conditions: ['Pre-existing diseases', 'ped'],
        page_number: 13,
        section_name: 'Section B - Waiting Periods',
        evidence_text: 'Pre-existing diseases declared at inception are covered only after 36 months of continuous coverage under the policy.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'star_3',
        category: 'room_rent',
        rule_name: 'Room Rent Proration Clause',
        value: 'Single Private Room',
        description: 'Proportionate deduction applied across surgeon, OT, and medical charges if Deluxe Suite is selected.',
        status: 'conditionally_covered',
        conditions: ['Single private AC room'],
        page_number: 6,
        section_name: 'Section A.1 - Room and Boarding',
        evidence_text: 'Room rent covered up to Single Private Room. In the event of admission to a higher category room, proportionate deduction shall apply to associated medical charges.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'star_4',
        category: 'sub_limit',
        rule_name: 'Normal Maternity Sub-Limit',
        value: '₹50,000',
        description: 'Normal delivery expenses capped at Rs 50,000 per delivery.',
        status: 'conditionally_covered',
        conditions: ['Normal delivery'],
        page_number: 9,
        section_name: 'Section A.4 - Maternity Benefits',
        evidence_text: 'Maternity expenses for normal delivery are subject to a sub-limit cap of Rs 50,000 per claim.',
        confidence: 'high',
        evidence_validated: true,
      },
      {
        id: 'star_5',
        category: 'co_payment',
        rule_name: 'Senior Citizen Co-pay (Age 61+)',
        value: '10%',
        description: '10% co-payment applied to claims for insured members aged 61 years or above.',
        status: 'conditionally_covered',
        conditions: ['Age >= 61'],
        page_number: 18,
        section_name: 'Section D - Co-payment',
        evidence_text: 'A 10% co-payment applies on every claim for persons who entered the policy aged 61 years or above.',
        confidence: 'high',
        evidence_validated: true,
      },
    ],
    pages: [
      { page_number: 4, text: 'Aggregate maximum indemnity shall not exceed the Sum Insured of Rs 10,00,000 as stated in the policy schedule.', char_count: 110 },
      { page_number: 6, text: 'Room rent covered up to Single Private Room. In the event of admission to a higher category room, proportionate deduction shall apply to associated medical charges.', char_count: 168 },
      { page_number: 9, text: 'Maternity expenses for normal delivery are subject to a sub-limit cap of Rs 50,000 per claim.', char_count: 92 },
      { page_number: 13, text: 'Pre-existing diseases declared at inception are covered only after 36 months of continuous coverage under the policy.', char_count: 118 },
      { page_number: 18, text: 'A 10% co-payment applies on every claim for persons who entered the policy aged 61 years or above.', char_count: 98 },
    ],
    total_pages: 34,
    scanned_pdf_warning: false,
    extraction_stats: {
      total_rules: 5,
      coverage_count: 1,
      exclusion_count: 0,
      waiting_period_count: 1,
      limit_count: 3,
      eligibility_count: 0,
      claim_requirement_count: 0,
      high_confidence: 5,
      medium_confidence: 0,
      low_confidence: 0,
      validated_count: 5,
    },
    processing_time_ms: 1100,
  },
}

// Automatically compile rules on export
for (const key of Object.keys(SAMPLE_POLICIES)) {
  const p = SAMPLE_POLICIES[key]
  p.compiled_rules = compilePolicyRules(p.rules, p.pages)
}
