/**
 * Reproducible demonstration of the claim ledger. Writes docs/claims/evidence.json and docs/claims/EVIDENCE.md:
 * version selection, item ledgers, calculation traces and before/after comparisons for the synthetic bills.
 * Run: npm run claims:demo
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { adjudicate, diffAdjudications } from '../lib/claims/adjudicate'
import { SAMPLE_CLAIM_BILLS, sampleVersions } from '../lib/claims/samples'
import type { AdjudicationResult } from '../lib/claims/types'

const inr = (n: number) => `Rs ${n.toLocaleString('en-IN')}`
const { base, amendment } = sampleVersions()

function ledgerTable(r: AdjudicationResult): string {
  const rows = r.items.map((i) => {
    const ded = i.deductions.length ? i.deductions.map((d) => `${d.stage} ${inr(d.amount)}`).join('; ') : '-'
    const clause = [...new Set(i.deductions.flatMap((d) => d.clauses.map((c) => `${c.ruleName} (${c.versionLabel}, p.${c.page ?? '?'})`)))].join('; ') || '-'
    const review = i.review.length ? i.review.join(' ') : '-'
    return `| ${i.description} | ${inr(i.claimed)} | ${inr(i.payable)} | ${i.status} | ${ded} | ${clause} | ${review} |`
  })
  return [
    '| Item | Claimed | Payable | Status | Deductions | Clause | Needs review |',
    '|---|---:|---:|---|---|---|---|',
    ...rows,
    `| **Total** | **${inr(r.totals.claimed)}** | **${inr(r.totals.payable)}** | | held for review ${inr(r.totals.heldForReview)} | | |`,
  ].join('\n')
}

const evidence: Record<string, unknown> = {}
let md = `# Claim ledger evidence\n\nGenerated by \`npm run claims:demo\`. All policy text and bills are **synthetic** (see lib/claims/samples.ts).\n\n`

for (const c of SAMPLE_CLAIM_BILLS) {
  const common = { items: c.bill.lineItems, bill: c.bill, patientAge: c.patientAge, policyStartDate: c.policyStartDate }
  const before = adjudicate({ ...common, versions: [base, amendment], treatmentDate: '2026-02-10' })
  const after = adjudicate({ ...common, versions: [base, amendment], treatmentDate: c.treatmentDate })
  const d = diffAdjudications(before, after)
  evidence[c.id] = { bill: c.title, before, after, diff: d }

  md += `## ${c.title}\n\n${c.shows}\n\n`
  md += `### Version selection\n\n- Treatment date before: 2026-02-10. Documents applied: ${before.selection.candidates.filter((x) => x.inForce).map((x) => x.label).join(' + ')}.\n`
  md += `- Treatment date after: ${c.treatmentDate}. Documents applied: ${after.selection.candidates.filter((x) => x.inForce).map((x) => x.label).join(' + ')}.\n`
  for (const x of after.selection.candidates) md += `  - ${x.label}: ${x.reason}\n`
  md += `\n### Before (base policy only)\n\n${ledgerTable(before)}\n\n### After (${c.treatmentDate}, endorsement in force)\n\n${ledgerTable(after)}\n\n`
  md += `**Change in payable amount:** ${inr(d.payableBefore)} to ${inr(d.payableAfter)} (${d.change < 0 ? '-' : '+'}${inr(Math.abs(d.change))}).\n\n`
  md += `### Calculation trace (after)\n\n${after.trace.map((t, i) => `${i + 1}. **${t.title}**: ${t.formula}${t.clause ? ` [${t.clause.versionLabel}, p.${t.clause.page}]` : ''}`).join('\n')}\n\n`
  md += `Checks: ${after.checks.ok ? 'passed (every item balances; no stage applied twice)' : after.checks.messages.join('; ')}\n\n`
}

mkdirSync('docs/claims', { recursive: true })
writeFileSync('docs/claims/evidence.json', JSON.stringify(evidence, null, 2))
writeFileSync('docs/claims/EVIDENCE.md', md)
console.log('Wrote docs/claims/evidence.json and docs/claims/EVIDENCE.md')
