import type { HospitalBill } from '@/lib/types/bill'

export const SAMPLE_HOSPITAL_BILLS: {
  id: string
  name: string
  hospital: string
  procedure: string
  total: string
  bill: HospitalBill
}[] = [
  {
    id: 'sample-knee-replacement',
    name: 'Max Healthcare — Knee Replacement',
    hospital: 'Max Super Speciality Hospital, New Delhi',
    procedure: 'Total Knee Arthroplasty (Right Knee)',
    total: '₹2,45,000',
    bill: {
      hospitalName: 'Max Super Speciality Hospital, Saket',
      patientName: 'Rahul Sharma (Age 58)',
      billNumber: 'MAX/2026/09/4821',
      billDate: '2026-09-15',
      admissionDate: '2026-09-11',
      dischargeDate: '2026-09-15',
      diagnosis: 'Severe Osteoarthritis Right Knee — TKR',
      totalBilledAmount: 245000,
      calculatedLineSum: 245000,
      lineToTotalDiscrepancy: 0,
      paymentSummary: {
        subtotal: 255000,
        discount: 10000,
        netPayable: 245000,
        deposit: 50000,
        amountPaid: 195000,
        balanceDue: 0,
      },
      totalPages: 3,
      extractionMethod: 'ai',
      parsingConfidence: 'high',
      warnings: [],
      lineItems: [
        {
          id: 'item_1',
          description: 'Single Deluxe AC Room (4 Days @ ₹8,000/day)',
          category: 'room',
          quantity: 4,
          unitPrice: 8000,
          amount: 32000,
          sourcePage: 1,
          originalText: 'Single Deluxe Room Charges (4 days @ 8000.00)',
          originalAmount: 32000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_2',
          description: 'Nursing & RMO Care Charges (4 Days)',
          category: 'room',
          quantity: 4,
          unitPrice: 2500,
          amount: 10000,
          sourcePage: 1,
          originalText: 'Nursing & Resident Doctor Care Charges',
          originalAmount: 10000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_3',
          description: 'Major Operation Theatre (OT) Charges',
          category: 'surgery',
          quantity: 1,
          unitPrice: 45000,
          amount: 45000,
          sourcePage: 1,
          originalText: 'OT Usage Tier 3 (Major Joint Arthroplasty)',
          originalAmount: 45000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_4',
          description: 'Chief Orthopaedic Surgeon Professional Fee',
          category: 'doctor',
          quantity: 1,
          unitPrice: 55000,
          amount: 55000,
          sourcePage: 1,
          originalText: 'Dr. V. Malhotra - Lead Surgeon Fee',
          originalAmount: 55000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_5',
          description: 'Senior Anaesthetist Consultation & Administration',
          category: 'doctor',
          quantity: 1,
          unitPrice: 15000,
          amount: 15000,
          sourcePage: 2,
          originalText: 'Anaesthesia Professional Charges',
          originalAmount: 15000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_6',
          description: 'Knee Prosthesis Implant (Depuy Attune CR)',
          category: 'implant',
          quantity: 1,
          unitPrice: 65000,
          amount: 65000,
          sourcePage: 2,
          originalText: 'Depuy Synthes Attune Fixed Bearing Knee Kit',
          originalAmount: 65000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_7',
          description: 'Pre-op & Post-op Diagnostics (Blood, ECG, X-Rays)',
          category: 'diagnostics',
          quantity: 1,
          unitPrice: 8500,
          amount: 8500,
          sourcePage: 2,
          originalText: 'Laboratory and Imaging Bundle (CBC, LFT, KFT, Digital X-Ray)',
          originalAmount: 8500,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_8',
          description: 'Inpatient Pharmacy & Antibiotic Injections',
          category: 'medicines',
          quantity: 1,
          unitPrice: 10500,
          amount: 10500,
          sourcePage: 3,
          originalText: 'Pharmacy - IV Fluids, Cefuroxime, Enoxaparin',
          originalAmount: 10500,
          confidence: 'medium',
          isUserEdited: false,
        },
        {
          id: 'item_9',
          description: 'Surgical Consumables & Sterile Disposables Kit',
          category: 'consumables',
          quantity: 1,
          unitPrice: 2000,
          amount: 2000,
          sourcePage: 3,
          originalText: 'OT Consumables, Gloves, Drapes & Sutures',
          originalAmount: 2000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_10',
          description: 'Hospital Administrative & Admission Processing',
          category: 'other',
          quantity: 1,
          unitPrice: 2000,
          amount: 2000,
          sourcePage: 3,
          originalText: 'Admin, Medical Records & Registration Fee',
          originalAmount: 2000,
          confidence: 'medium',
          isUserEdited: false,
        },
      ],
    },
  },
  {
    id: 'sample-appendectomy',
    name: 'Apollo Hospitals — Appendectomy',
    hospital: 'Apollo Hospitals, Bengaluru',
    procedure: 'Laparoscopic Appendectomy',
    total: '₹92,400',
    bill: {
      hospitalName: 'Apollo Hospitals, Bannerghatta Road',
      patientName: 'Priya Sundaram (Age 32)',
      billNumber: 'APL-BLR-2026-88192',
      billDate: '2026-09-20',
      admissionDate: '2026-09-18',
      dischargeDate: '2026-09-20',
      diagnosis: 'Acute Appendicitis',
      totalBilledAmount: 92400,
      calculatedLineSum: 92400,
      lineToTotalDiscrepancy: 0,
      paymentSummary: {
        subtotal: 95400,
        discount: 3000,
        netPayable: 92400,
        deposit: 25000,
        amountPaid: 67400,
        balanceDue: 0,
      },
      totalPages: 2,
      extractionMethod: 'ai',
      parsingConfidence: 'high',
      warnings: [],
      lineItems: [
        {
          id: 'item_1',
          description: 'Twin Sharing Room Rent (2 Days @ ₹4,500/day)',
          category: 'room',
          quantity: 2,
          unitPrice: 4500,
          amount: 9000,
          sourcePage: 1,
          originalText: 'Twin Sharing Ward (2 Days)',
          originalAmount: 9000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_2',
          description: 'Laparoscopic Appendectomy Procedure Charges',
          category: 'surgery',
          quantity: 1,
          unitPrice: 38000,
          amount: 38000,
          sourcePage: 1,
          originalText: 'Lap Appendectomy Theatre & Equipment',
          originalAmount: 38000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_3',
          description: 'General Surgeon & Anaesthesia Consultation',
          category: 'doctor',
          quantity: 1,
          unitPrice: 15000,
          amount: 15000,
          sourcePage: 1,
          originalText: 'Surgeon Fee + Anaesthetist Charge',
          originalAmount: 15000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_4',
          description: 'Inpatient Pharmacy & IV Antibiotics',
          category: 'medicines',
          quantity: 1,
          unitPrice: 14200,
          amount: 14200,
          sourcePage: 2,
          originalText: 'Pharmacy - IV Paracetamol, Metrogyl, Augmentin',
          originalAmount: 14200,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_5',
          description: 'Diagnostic Ultrasound Abdomen & Blood Tests',
          category: 'diagnostics',
          quantity: 1,
          unitPrice: 4800,
          amount: 4800,
          sourcePage: 2,
          originalText: 'USG Whole Abdomen, Complete Blood Count, Urine Routine',
          originalAmount: 4800,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_6',
          description: 'Laparoscopic Disposable Trocars & Consumables Kit',
          category: 'consumables',
          quantity: 1,
          unitPrice: 8400,
          amount: 8400,
          sourcePage: 2,
          originalText: 'Surgical Drapes, Cannula, Lap Trocars',
          originalAmount: 8400,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_7',
          description: 'Hospital Bio-Waste & Documentation Surcharge',
          category: 'other',
          quantity: 1,
          unitPrice: 3000,
          amount: 3000,
          sourcePage: 2,
          originalText: 'Bio-medical Waste Disposal & Discharge Documentation',
          originalAmount: 3000,
          confidence: 'medium',
          isUserEdited: false,
        },
      ],
    },
  },
  {
    id: 'sample-cardiac-anomalies',
    name: 'Fortis Escorts — Angioplasty (Audit Test Case)',
    hospital: 'Fortis Escorts Heart Institute, New Delhi',
    procedure: 'PTCA with Drug Eluting Stent',
    total: '₹2,16,000',
    bill: {
      hospitalName: 'Fortis Escorts Heart Institute, Okhla',
      patientName: 'Sunil Verma (Age 54)',
      billNumber: 'FEHI-PTCA-2026-10492',
      billDate: '2026-09-28',
      admissionDate: '2026-09-26',
      dischargeDate: '2026-09-28',
      diagnosis: 'Coronary Artery Disease — Single Vessel Stenting',
      totalBilledAmount: 216000,
      calculatedLineSum: 216000,
      lineToTotalDiscrepancy: 0,
      paymentSummary: {
        subtotal: 220000,
        discount: 4000,
        netPayable: 216000,
        deposit: 50000,
        amountPaid: 166000,
        balanceDue: 0,
      },
      totalPages: 3,
      extractionMethod: 'ai',
      parsingConfidence: 'high',
      warnings: [],
      lineItems: [
        {
          id: 'item_1',
          description: 'Coronary Care Unit (CCU/ICU) Bed (2 Days @ ₹12,000/day)',
          category: 'icu',
          quantity: 2,
          unitPrice: 12000,
          amount: 24000,
          sourcePage: 1,
          originalText: 'CCU Bed Charges (2 Days @ 12000)',
          originalAmount: 24000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_2',
          description: 'Drug Eluting Coronary Stent (DES)',
          category: 'implant',
          quantity: 1,
          unitPrice: 45000,
          amount: 45000,
          sourcePage: 1,
          originalText: 'Resolute Onyx Zotarolimus-Eluting Coronary Stent',
          originalAmount: 45000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_3',
          description: 'Coronary Stent Device Charge',
          category: 'implant',
          quantity: 1,
          unitPrice: 45000,
          amount: 45000,
          sourcePage: 2,
          originalText: 'Coronary Stenting System Device',
          originalAmount: 45000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_4',
          description: 'Chief Interventional Cardiologist Procedure Fee',
          category: 'doctor',
          quantity: 1,
          unitPrice: 40000,
          amount: 48000,
          sourcePage: 2,
          originalText: 'Dr. A. Seth - Primary Angioplasty Fee',
          originalAmount: 48000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_5',
          description: 'Cath Lab Operation & Fluoroscopy Equipment Usage',
          category: 'surgery',
          quantity: 1,
          unitPrice: 30000,
          amount: 30000,
          sourcePage: 2,
          originalText: 'Cath Lab Facility & Digital Angiography Suite',
          originalAmount: 30000,
          confidence: 'high',
          isUserEdited: false,
        },
        {
          id: 'item_6',
          description: 'Miscellaneous Hospital Charges',
          category: 'other',
          quantity: 1,
          unitPrice: 17500,
          amount: 17500,
          sourcePage: 3,
          originalText: 'Misc Hospital Charges & Sundry Services',
          originalAmount: 17500,
          confidence: 'medium',
          isUserEdited: false,
        },
        {
          id: 'item_7',
          description: 'Surgical Consumables, Syringes & PPE Kit',
          category: 'consumables',
          quantity: 1,
          unitPrice: 6500,
          amount: 6500,
          sourcePage: 3,
          originalText: 'Cath Lab Disposables, Guide Wire, Syringes & PPE Kit',
          originalAmount: 6500,
          confidence: 'high',
          isUserEdited: false,
        },
      ],
    },
  },
]

